### ISSUE TITLE
Multiple selections don't show up

### ISSUE THREAD

**Issue by atishay** [yaddran/brackets-occurrences-marker#5]
Select a word and press Cmd + B to get into multiple selection mode. The highlight prevents the new selections form showing up making it very difficult to find out what is selected.

**Comment by yaddran** [comment]
Hi, I am sorry but I was away from the project for some time. I will try to do something as soon as possible. Thank you for understanding.

**Comment by yaddran** [comment]
Solved in version v1.0.4
