### ISSUE TITLE
Marking by mouse invisible when occurrences-marker marks text

### ISSUE THREAD

**Issue by treeno** [yaddran/brackets-occurrences-marker#6]
First, thank you for your nice plugin!
I have noticed a small inconvenience. If I try to select text i.e. for c&p I cannot see the mouse-selection because the occurrences-marker seems to override it.
The color could be inverted, or an alpha channel could be used to mix the color of both markings, so that a difference will be visible.
Maybe you can find some time to add that feature :-)

**Comment by yaddran** [comment]
Hi, I am sorry but I was away from the project for some time. I will try to do something as soon as possible. Thank you for understanding.

**Comment by yaddran** [comment]
Solved in version v1.0.4
